spring:
  application.name: lambda-core
  # prevents put body from being eaten as form params // whatever
  mvc.formcontent.filter.enabled: false
  # async http requests default 30s container timeout overwrite
  mvc.async.request-timeout: -1
  datasource:
    url: ${LAMBDA_DB_URL:jdbc:postgresql://localhost:5432/lambda}
    username: ${LAMBDA_DB_USER:lambda}
    password: ${LAMBDA_DB_PASSWORD:lambda}
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
    properties.hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true

server.port: ${LAMBDA_PORT:8080}

lambda.storage:
  root: ${LAMBDA_STORAGE_ROOT:./data}
  # 2gb
  max-file-bytes: ${LAMBDA_MAX_FILE_BYTES:2147483648}

logging.level:
  com.microchip.lambda_core: INFO
